### PR TITLE
Fancy Select 

### PR DESCRIPTION
**Pull request by nastiatikk**
Status: Opened for visibility

Reviewers: @tedtate @kpeatt @jeffkamo @ry5n @avelinet @cole-sanderson @mlworks @yourpalsonja 

Stencil Fancy-Select component moved into its own repo from https://github.com/mobify/stencil-select/pull/2

Notes:
- This component dependent on [PR-67](https://github.com/mobify/vellum/pull/67) Vellum changes

### CODE REVIEW

**Comment by ry5n** [comment]
@zacharyhalvorson test

**Comment by kpeatt** [comment]
@ry5n test

**Comment by tedtate** [comment]
@kpeatt ah-ah-ah-magic-word

**Comment by tedtate** [comment]
Test

**Pull request merged**
